# Generated by Django 5.0.4 on 2024-04-23 20:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='title', unique=True),
        ),
    ]
